"""Add coverage area columns to pointcloud

Revision ID: 2a8bb57d7d91
Revises: 007_add_measurements_table
Create Date: 2025-11-06 18:44:05.039179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a8bb57d7d91'
down_revision = '007_add_measurements_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    if "measurements" not in inspector.get_table_names():
        op.create_table(
            "measurements",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("pointcloud_id", sa.Integer(), nullable=False),
            sa.Column("point1_x", sa.Float(), nullable=False),
            sa.Column("point1_y", sa.Float(), nullable=False),
            sa.Column("point1_z", sa.Float(), nullable=False),
            sa.Column("point2_x", sa.Float(), nullable=False),
            sa.Column("point2_y", sa.Float(), nullable=False),
            sa.Column("point2_z", sa.Float(), nullable=False),
            sa.Column("distance", sa.Float(), nullable=False),
            sa.Column("label", sa.String(), nullable=True),
            sa.Column("metadata_json", sa.JSON(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint("id"),
            sa.ForeignKeyConstraint(["pointcloud_id"], ["pointclouds.id"], ondelete="CASCADE"),
        )
        op.create_index(op.f("ix_measurements_id"), "measurements", ["id"], unique=False)
        op.create_index(op.f("ix_measurements_pointcloud_id"), "measurements", ["pointcloud_id"], unique=False)
    op.alter_column('classification_edit_batches', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('classification_edit_batches', 'operations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('classification_edit_batches', 'error_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('pointclouds', sa.Column('coverage_area_km2', sa.Float(), nullable=True))
    op.add_column('pointclouds', sa.Column('coverage_area_sqft', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pointclouds', 'coverage_area_sqft')
    op.drop_column('pointclouds', 'coverage_area_km2')
    op.alter_column('classification_edit_batches', 'error_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('classification_edit_batches', 'operations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('classification_edit_batches', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
